language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
addons:
  sonarcloud:
    organization: ben1lam8-github
# command to run tests
script:
  - pytest --cov .
  - sonar-scanner
  - coveralls
